version: '3.0'

services:
  ogr_api:
    image: africahazardswatch.org/ogr-api
    container_name: ogr_api
    build: .
    restart: ${RESTART_POLICY}
    command: start
    environment:
      - PORT=3000
      - LOGGER_LEVEL=${LOGGER_LEVEL}
    ports:
      - ${PORT}:3000

networks:
    default:
      name:  ${AHW_DOCKER_NETWORK}
      external: true